### ISSUE TITLE
Error when starting Directus from version 10.6.2 and up

### ISSUE THREAD

**Issue by caklein** [resauce-dev/directus-image-scout#22] opened 2023-10-09 16:44 UTC
Hello!

I hope this message finds you well. I would like to bring to your attention an issue I have encountered while using your incredibly valuable extension on Directus 10.6.2 (docker).

Upon attempting to start Directus for the first time, I encountered the following fatal error:

directus-custom-directus-1  | Error: Cannot find module 'axios'
directus-custom-directus-1  | Require stack:
directus-custom-directus-1  | - /directus/extensions/endpoints/resauce-image-scout/classes/Provider.cjs
directus-custom-directus-1  | - /directus/extensions/endpoints/resauce-image-scout/providers/giphy.cjs
directus-custom-directus-1  | - /directus/extensions/endpoints/resauce-image-scout/providers.cjs
directus-custom-directus-1  | - /directus/extensions/endpoints/resauce-image-scout/index.cjs
directus-custom-directus-1  |     at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
directus-custom-directus-1  |     at Module._load (node:internal/modules/cjs/loader:922:27)
directus-custom-directus-1  |     at Module.require (node:internal/modules/cjs/loader:1143:19)
directus-custom-directus-1  |     at require (node:internal/modules/cjs/helpers:121:18)
directus-custom-directus-1  |     at Object.<anonymous> (/directus/extensions/endpoints/resauce-image-scout/classes/Provider.cjs:1:15)
directus-custom-directus-1  |     at Module._compile (node:internal/modules/cjs/loader:1256:14)
directus-custom-directus-1  |     at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
directus-custom-directus-1  |     at Module.load (node:internal/modules/cjs/loader:1119:32)
directus-custom-directus-1  |     at Module._load (node:internal/modules/cjs/loader:960:12)
directus-custom-directus-1  |     at Module.require (node:internal/modules/cjs/loader:1143:19) {
directus-custom-directus-1  |   code: 'MODULE_NOT_FOUND',
directus-custom-directus-1  |   requireStack: [
directus-custom-directus-1  |     '/directus/extensions/endpoints/resauce-image-scout/classes/Provider.cjs',
directus-custom-directus-1  |     '/directus/extensions/endpoints/resauce-image-scout/providers/giphy.cjs',
directus-custom-directus-1  |     '/directus/extensions/endpoints/resauce-image-scout/providers.cjs',
directus-custom-directus-1  |     '/directus/extensions/endpoints/resauce-image-scout/index.cjs'
directus-custom-directus-1  |   ]
directus-custom-directus-1  | }
directus-custom-directus-1  | 
directus-custom-directus-1  | Node.js v18.17.1
directus-custom-directus-1 exited with code 1

It's worth noting that this error was not present in version 10.6.1, where everything was working flawlessly.

I kindly request your assistance in resolving this matter, as your extension has been an invaluable asset to our workflow, and we greatly appreciate your support in ensuring its continued functionality.

**Comment by shealavington** [comment] 2023-10-09 22:27
Hi 👋,

Thank you for raising this, I appreciate the time taken. I will take a look tomorrow.

Thanks

**Comment by shealavington** [comment] 2023-10-10 16:20
I can confirm the issue is there for Directus `10.6.2` and not for `v10.6.1`. 
I will look into this and create an update for `v10.6.2` shortly.

**Comment by shealavington** [comment] 2023-10-10 21:46
This issue has been resolved in the [latest release](https://github.com/resauce-dev/directus-image-scout/releases/tag/v3.1.2)
I appreciate the time taken to raise this issue. 🍪

**Closed by shealavington** 2023-10-10 21:46 UTC
Labels: bug

**Comment by caklein** [comment] 2023-10-11 17:04
Thank you for your promptness!

I'm not sure if it's related, but I began encountering Error 500 when trying to select an image from any provider after updating both the plugin and Directus.

![image](https://github.com/resauce-dev/directus-image-scout/assets/2090811/105ceaa9-2832-4778-883b-ea8258f6bb58)

**Comment by shealavington** [comment] 2023-10-11 18:51
> Thank you for your promptness!
> 
> I'm not sure if it's related, but I began encountering Error 500 when trying to select an image from any provider after updating both the plugin and Directus.
> 
> ![image](https://github.com/resauce-dev/directus-image-scout/assets/2090811/105ceaa9-2832-4778-883b-ea8258f6bb58)
> 

Interesting, I went through and checked all 4 providers with my keys, so it definitely works.

I don't suppose there were any errors out into the docker logs? I believe I've prefixed all of my errors with '🎨', it could help would out what the root cause is.

I do aim at some point to make the error logging more helpful. So I do apologise that it might not be the best for now, unfortunately time is tight 😅

I've just looked at `triggerDownload`, and the line that is failing is when it tries to post the image data to Directus. With that, it could be a docker permissions issue. — I had an issue myself  (see [issue comment](https://github.com/directus/directus/issues/19543#issuecomment-1756177719)) while mounting a storage directory, do you have an upload directory mounted to the host machine?

Something may have changed in Directus recently as I never used to have issues with mounting a directory.

**Comment by caklein** [comment] 2023-10-13 08:40
Got this:
![image](https://github.com/resauce-dev/directus-image-scout/assets/2090811/c7e90c31-dd15-4d54-84db-2e56e184bd92)

In my case, I did the following:
* Clicked on "Browse Images" on a field configured as Image Scout.
* The default search results were displayed correctly, and I selected an image by clicking on the image selector.
* Clicked on "Save."
* However, the message "Please wait while we process your request" continued to be displayed indefinitely.

I am using Directus 10.6.3.

**Comment by shealavington** [comment] 2023-10-13 09:24
Thanks for sharing the detailed information, as it helps alot. 

Unfortunately, I can only think that there appears to be an issue on your side of things somewhere. I've tried to replicate the same setup as you, however, everything is working here (image attached ~2).

It appears that it might be failing during the process of posting the prepared data to Directus. Are you able to see if the request looks malformed in any way in the network tab? ~1

~1
![image](https://github.com/resauce-dev/directus-image-scout/assets/16869302/211e2f88-9016-4acc-b25a-ec2b8c80bc62)


~2
![image](https://github.com/resauce-dev/directus-image-scout/assets/16869302/d9a9106f-8dc0-4c62-949e-50b4248b7484)
